### ISSUE TITLE
hash function for symbol key strings to ints

### ISSUE THREAD

**Issue by ghost** [rigtorp/spartan#2]
to map from symbol name to an int (which then can be used to index an array)

i think this is the fastest way to map a symbol name to a unique int. i think its faster than a trie as well.

$ gperf -e '\n' -L C++ -7 -C -E -k '*,1,$' -m 6 symbols.txt > perfhash.cpp

the '-m 6' indicates 6 elements in list.csv

test it out yourself, then look at perfhash.cpp

it will create a perfect hash function

create symbols.txt with 6 symbol names in it like:
MSFT
AAPL
AA
ZG
T
A

**Comment by rigtorp** [comment]
I'm aware of perfect hashing. Have you tried benchmarking it? It's less robust (need to regenerate when symbols are added) so I doubt it's worthwhile.

**Comment by ghost** [comment]
thats true you do need to add when you add new symbols

**Comment by ghost** [comment]
but the latency will be lower because its just pure arithmetic vs branching

**Comment by rigtorp** [comment]
With a open addressing hash table with linear probing (what I'm using) all
branches are predictable when there is no collision. You could use the
perfect hash as the integer finalizer and get zero collisions in the common
case, but robustness if new symbols are added.

**Comment by ghost** [comment]
Have you tried using a trie with each node a struct containing a letter and
the integer key if you have reached the final node

**Comment by rigtorp** [comment]
No, I suspect it'll be bad. Lots of branch misspredictions and a cache
unfriendly memory access pattern.

**Comment by ghost** [comment]
You never need to add symbols in the middle of he day - I think the best
way to do it is to recompile the perfect hash function when there are
symbol changes
